import { existsSync } from "node:fs";
import { readFile } from "node:fs/promises";

import { join } from "pathe";

import { buildAgentReadability } from "../ai/agent-readability.ts";
import {
  API_CATALOG_PATH,
  API_CATALOG_TYPE,
  buildApiCatalog,
} from "../ai/api-catalog.ts";
import { buildLlmsFiles } from "../ai/llms.ts";
import type { BlumeProject } from "../core/project-graph.ts";
import { routeIsTaken } from "./pages.ts";

interface ArtifactFile {
  path: string;
  content: string;
  pattern?: string;
}

const textEndpoint = (body: string, type: string): string =>
  `// Generated by Blume. Do not edit.\nexport const prerender = true;\nexport const GET = () => new Response(${JSON.stringify(body)}, { headers: { "Content-Type": ${JSON.stringify(`${type}; charset=utf-8`)} } });\n`;

/** Snapshot endpoints also work in dev and in the standalone ejected app. */
export const agentArtifactFiles = async (
  project: BlumeProject,
  srcDir: string,
  userPages: { pattern: string }[]
): Promise<ArtifactFile[]> => {
  const { config, context } = project;
  const bases = [...new Set(["", config.basePath])];
  const artifacts: { name: string; body: string; type: string }[] = [];
  if (config.ai.llmsTxt.enabled) {
    const llms = await buildLlmsFiles(project);
    artifacts.push(
      { body: llms.index, name: "llms.txt", type: "text/plain" },
      { body: llms.full, name: "llms-full.txt", type: "text/plain" }
    );
  }
  const manifest = buildAgentReadability(project);
  if (
    config.ai.api &&
    existsSync(join(context.root, "public", "openapi.json"))
  ) {
    artifacts.push({
      body: "",
      name: "openapi.json",
      type: "application/json",
    });
  }
  if (manifest) {
    artifacts.push({
      body: `${JSON.stringify(manifest, null, 2)}\n`,
      name: "agent-readability.json",
      type: "application/json",
    });
  }
  const files: ArtifactFile[] = [];
  const catalog = buildApiCatalog(config);
  if (
    catalog &&
    !existsSync(join(context.root, "public", API_CATALOG_PATH)) &&
    !routeIsTaken(userPages, project.graph.pages, API_CATALOG_PATH)
  ) {
    files.push({
      content: textEndpoint(catalog, API_CATALOG_TYPE),
      path: join(srcDir, "blume-artifacts", "catalog.ts"),
      pattern: API_CATALOG_PATH,
    });
  }
  const artifactFiles = await Promise.all(
    artifacts.map(async (artifact) => {
      const generated: ArtifactFile[] = [];
      const rootPublic = join(context.root, "public", artifact.name);
      const body = existsSync(rootPublic)
        ? await readFile(rootPublic, "utf-8")
        : artifact.body;
      for (const base of bases) {
        const route = `${base}/${artifact.name}`;
        if (
          existsSync(join(context.root, "public", route)) ||
          routeIsTaken(userPages, project.graph.pages, route)
        ) {
          continue;
        }
        generated.push({
          content: textEndpoint(body, artifact.type),
          path: join(srcDir, "pages", `${route}.ts`),
        });
      }
      return generated;
    })
  );
  return [...files, ...artifactFiles.flat()];
};
