import { afterEach, expect, it } from "bun:test";
import { existsSync } from "node:fs";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";

import { dirname, join } from "pathe";

import { buildAgentReadability } from "../src/ai/agent-readability.ts";
import { buildApiCatalog } from "../src/ai/api-catalog.ts";
import {
  apiNotFoundResponse,
  buildPagesIndex,
  pageResponse,
} from "../src/ai/api/handlers.ts";
import {
  artifactRoute,
  deployedArtifactRoute,
} from "../src/ai/artifact-routes.ts";
import { buildHomeLinkHeader } from "../src/ai/link-headers.ts";
import { buildLlmsIndex } from "../src/ai/llms.ts";
import { buildMcpData } from "../src/ai/mcp/data.ts";
import { buildMcpDiscovery } from "../src/ai/mcp/discovery.ts";
import { buildRuntimeData, generateRuntime } from "../src/astro/generate.ts";
import { askEndpoint } from "../src/core/ask-route.ts";
import { packageRoot } from "../src/core/package-root.ts";
import { scanProject } from "../src/core/project-graph.ts";
import { blumeConfigSchema } from "../src/core/schema.ts";
import { eject } from "../src/registry/eject.ts";

const roots: string[] = [];
afterEach(async () => {
  await Promise.all(
    roots.splice(0).map((root) => rm(root, { force: true, recursive: true }))
  );
});

const fixture = async (config: string) => {
  const root = await mkdtemp(join(tmpdir(), "blume-mount-"));
  roots.push(root);
  await mkdir(join(root, "docs"));
  await writeFile(
    join(root, "docs", "index.md"),
    "---\ntitle: Welcome\n---\nHello docs."
  );
  await writeFile(join(root, "blume.config.ts"), `export default ${config}`);
  return root;
};

const transform = () => null;

it("removes obsolete generated API namespace files on eject without deleting authored endpoints", async () => {
  const root = await fixture('{ basePath: "/docs" }');
  await eject(root);
  await writeFile(
    join(root, "src/pages/api/docs/index.ts"),
    "// User-owned endpoint\nexport const GET = () => new Response('owned');"
  );
  await writeFile(
    join(root, "src/pages/docs/api/docs/index.ts"),
    "// Generated by Blume. Do not edit.\nexport const GET = () => new Response('{}');"
  );
  await writeFile(
    join(root, "blume.config.ts"),
    'export default { basePath: "/new" }'
  );
  await eject(root);
  expect(existsSync(join(root, "src/pages/docs/api/docs/index.ts"))).toBe(
    false
  );
  expect(existsSync(join(root, "src/pages/api/docs/index.ts"))).toBe(true);
  expect(existsSync(join(root, "src/pages/new/api/docs/pages.json.ts"))).toBe(
    true
  );
});

it("keeps mounted content and custom API rest pages ahead of the JSON catch-all", async () => {
  const root = await fixture(
    '{ basePath: "/docs", deployment: { output: "server", adapter: "node" } }'
  );
  await mkdir(join(root, "docs/api"));
  await writeFile(
    join(root, "docs/api/guide.md"),
    "# API guide\nContent must remain reachable."
  );
  const contentProject = await scanProject(root);
  await generateRuntime(contentProject);
  const pages = join(contentProject.context.outDir, "src/pages");
  expect(existsSync(join(pages, "api/[...path].ts"))).toBe(true);
  expect(existsSync(join(pages, "docs/api/[...path].ts"))).toBe(false);
  expect(existsSync(join(pages, "docs/api/docs/pages.json.ts"))).toBe(true);

  await rm(join(root, "docs/api/guide.md"));
  await mkdir(join(root, "pages/docs/api"), { recursive: true });
  await writeFile(
    join(root, "pages/docs/api/[...custom].astro"),
    "---\nexport const prerender = false;\n---\nCustom API owner"
  );
  await generateRuntime(await scanProject(root));
  expect(existsSync(join(pages, "api/[...path].ts"))).toBe(true);
  expect(existsSync(join(pages, "docs/api/[...path].ts"))).toBe(false);
  const config = await readFile(
    join(contentProject.context.outDir, "astro.config.mjs"),
    "utf-8"
  );
  expect(config).toContain('"pattern":"/docs/api/[...custom]"');
});

const runRuntimeFixture = async (
  args: string[],
  timeout: number
): Promise<void> => {
  const child = Bun.spawn(
    [
      process.execPath,
      join(packageRoot(), "test/mounted-runtime.fixture.ts"),
      ...args,
    ],
    { stderr: "pipe", stdout: "pipe" }
  );
  try {
    const [code, stdout, stderr] = await Promise.race([
      Promise.all([
        child.exited,
        new Response(child.stdout).text(),
        new Response(child.stderr).text(),
      ]),
      Bun.sleep(timeout).then(() => {
        throw new Error("Mounted runtime probe timed out");
      }),
    ]);
    expect({ code, output: code === 0 ? "" : `${stdout}\n${stderr}` }).toEqual({
      code: 0,
      output: "",
    });
  } finally {
    child.kill();
  }
};

it("serves mounted artifacts and executable Vite plugins in generated and ejected dev apps", async () => {
  await runRuntimeFixture([], 65_000);
}, 75_000);

it("builds and previews root and mounted JSON APIs without file-directory collisions before and after eject", async () => {
  await runRuntimeFixture(["--build"], 240_000);
}, 250_000);

it("resolves Ask defaults and explicit URLs without rebasing overrides", () => {
  for (const [basePath, base, expected] of [
    ["", "", "/api/ask"],
    ["/docs", "", "/docs/api/ask"],
    ["/docs/nested", "/host", "/host/docs/nested/api/ask"],
    ["/docs", "/docs", "/docs/docs/api/ask"],
    ["/docs/nested", "/docs", "/docs/docs/nested/api/ask"],
    ["/api", "/api", "/api/api/api/ask"],
  ] as const) {
    expect(
      askEndpoint(blumeConfigSchema.parse({ basePath, deployment: { base } }))
    ).toBe(expected);
  }
  for (const endpoint of ["/custom/ask", "https://ask.test/chat"]) {
    expect(
      askEndpoint(
        blumeConfigSchema.parse({
          ai: { ask: { endpoint } },
          basePath: "/docs",
          deployment: { base: "/host" },
        })
      )
    ).toBe(endpoint);
  }
});

it("keeps overlapping deployment and content layers in manifests, API bodies and recovery links", async () => {
  const root = await fixture(
    '{ basePath: "/docs", deployment: { base: "/docs", site: "https://docs.test" }, ai: { ask: { enabled: true } } }'
  );
  const project = await scanProject(root);
  const manifest = buildAgentReadability(project);
  expect(manifest?.artifacts.askApi).toBe(
    "https://docs.test/docs/docs/api/ask"
  );
  expect(manifest?.artifacts.llmsTxt).toBe(
    "https://docs.test/docs/docs/llms.txt"
  );
  expect(manifest?.artifacts.markdown.pattern).toBe(
    "https://docs.test/docs/docs/{route}.md"
  );
  const data = await buildMcpData(project);
  expect(
    buildMcpDiscovery({
      base: "/docs",
      name: "Docs",
      route: "/docs/mcp",
      site: null,
      version: "1",
    }).servers[0]?.url
  ).toBe("/docs/docs/mcp");
  const index = buildPagesIndex(data);
  expect(index.pages[0]?.json).toBe(
    "https://docs.test/docs/docs/api/docs/pages/docs.json"
  );
  expect(index.pages[0]?.markdownUrl).toBe("https://docs.test/docs/docs.md");
  expect(index.pages[0]?.url).toBe("https://docs.test/docs/docs");
  const missing = pageResponse(data, "/missing");
  expect(await missing.text()).toContain(
    "https://docs.test/docs/docs/api/docs/pages.json"
  );
  const recovery = apiNotFoundResponse(
    new Request("https://docs.test/docs/docs/api/unknown"),
    data
  );
  expect(await recovery.text()).toContain(
    "https://docs.test/docs/docs/openapi.json"
  );
  expect(buildApiCatalog(project.config)).toContain(
    '"href": "https://docs.test/docs/docs"'
  );
});

it("normalizes asset namespaces and preserves executable plugin options", () => {
  const plugin = { name: "user-plugin", transform };
  const config = blumeConfigSchema.parse({
    publicAssetBasePath: " docs-assets// ",
    vite: { plugins: [false, [plugin]] },
  });
  expect(config.publicAssetBasePath).toBe("/docs-assets");
  expect(config.vite.plugins[1]).toEqual([plugin]);
  expect(blumeConfigSchema.parse({}).publicAssetBasePath).toBe("");
  expect(blumeConfigSchema.parse({}).ai.mcp.discovery).toBe(true);
});

it("distinguishes artifacts from explicit routes and already based paths", () => {
  expect(deployedArtifactRoute("/docs/", "/docs", "/llms.txt")).toBe(
    "/docs/docs/llms.txt"
  );
  for (const path of [
    "/mcp",
    "/.well-known/mcp.json",
    "https://remote.test/api/docs",
    "/docs/llms.txt",
  ]) {
    expect(artifactRoute("/docs", path)).toBe(path);
  }
  expect(artifactRoute("/docs", "/api/docs/pages.json")).toBe(
    "/docs/api/docs/pages.json"
  );
  expect(artifactRoute("", "/llms.txt")).toBe("/llms.txt");
});

it("generates mounted Ask, artifacts and API aliases, then prunes moved and disabled endpoints", async () => {
  const root = await fixture(
    `{ basePath: "/docs/nested", deployment: { base: "/host" }, ai: { ask: { enabled: true }, mcp: { enabled: true, discovery: false, route: "/docs/mcp" } } }`
  );
  const project = await scanProject(root);
  await generateRuntime(project);
  const pages = join(project.context.outDir, "src", "pages");
  const ask = await readFile(join(pages, "docs/nested/api/ask.ts"), "utf-8");
  expect(ask).toContain('from "blume:ask-data"');
  expect(buildRuntimeData(project)).toContain(
    '"endpoint": "/host/docs/nested/api/ask"'
  );
  expect(buildAgentReadability(project)?.artifacts.askApi).toBe(
    "/host/docs/nested/api/ask"
  );
  expect(buildAgentReadability(project)?.artifacts.mcp).toEqual({
    url: "/host/docs/mcp",
  });
  expect(buildLlmsIndex(project)).not.toContain("/.well-known/mcp.json");
  expect(buildApiCatalog(project.config)).not.toContain(
    "/.well-known/mcp.json"
  );
  expect(buildHomeLinkHeader(project.config, ["/"])).toContain(
    "/host/docs/nested/openapi.json"
  );
  expect(existsSync(join(pages, "api/docs/pages.json.ts"))).toBe(true);
  expect(existsSync(join(pages, "docs/nested/api/docs/pages.json.ts"))).toBe(
    true
  );
  const spec = await readFile(
    join(pages, "docs/nested/openapi.json.ts"),
    "utf-8"
  );
  expect(spec).not.toContain("/.well-known/mcp.json");
  const endpoint = await import(join(pages, "docs/nested/llms.txt.ts"));
  const response: Response = endpoint.GET();
  expect(response.headers.get("Content-Type")).toBe(
    "text/plain; charset=utf-8"
  );
  expect(await response.text()).toContain(
    "/host/docs/nested/api/docs/pages.json"
  );
  expect(
    existsSync(join(project.context.outDir, "src/blume-mcp/discovery.ts"))
  ).toBe(false);
  project.config.basePath = "/new";
  await generateRuntime(project);
  expect(existsSync(join(pages, "docs/nested/api/ask.ts"))).toBe(false);
  expect(existsSync(join(pages, "new/api/ask.ts"))).toBe(true);
  if (project.config.ai.ask) {
    project.config.ai.ask.enabled = false;
  }
  await generateRuntime(project);
  expect(existsSync(join(pages, "new/api/ask.ts"))).toBe(false);
});

it("ejects mounted endpoints, public icon variants and a plugins-only config bridge", async () => {
  const root = await fixture(
    `{ basePath: "/docs", publicAssetBasePath: "/docs-assets", vite: { plugins: [{ name: "user", transform: () => null }] }, ai: { ask: { enabled: true, provider: "inkeep" }, mcp: { enabled: true, discovery: false } } }`
  );
  await Promise.all(
    ["icon.svg", "icon-dark.svg", "apple-icon.png"].map(async (name) => {
      const path = join(root, "public/docs-assets", name);
      await mkdir(dirname(path), { recursive: true });
      await writeFile(path, "icon");
    })
  );
  const result = await eject(root);
  expect(result.files).toContain(join(root, "src/pages/docs/api/ask.ts"));
  const ask = await readFile(join(root, "src/pages/docs/api/ask.ts"), "utf-8");
  expect(ask).not.toContain("blume:ask-data");
  expect(existsSync(join(root, "src/pages/docs/api/docs/pages.json.ts"))).toBe(
    true
  );
  expect(existsSync(join(root, "src/pages/docs/llms.txt.ts"))).toBe(true);
  const config = await readFile(join(root, "astro.config.mjs"), "utf-8");
  expect(config).toContain('assets: "docs-assets/_astro"');
  expect(config).toContain("...(blumeConfig?.vite?.plugins ?? [])");
  expect(config).toContain("loadBlumeConfig");
  expect(config).not.toContain("/.well-known/mcp.json");
  const data = JSON.parse(
    await readFile(join(root, "src/generated/data.json"), "utf-8")
  );
  expect(data.config.favicon.href).toBe("/docs-assets/icon.svg");
  expect(data.config.favicon.dark.href).toBe("/docs-assets/icon-dark.svg");
  expect(data.config.appleIcon.href).toBe("/docs-assets/apple-icon.png");
  await writeFile(
    join(root, "blume.config.ts"),
    'export default { basePath: "/new", ai: { ask: { enabled: false }, mcp: { enabled: true, discovery: false } } }'
  );
  await eject(root);
  expect(existsSync(join(root, "src/pages/docs/api/ask.ts"))).toBe(false);
});

it("preserves explicit Ask endpoints and user-owned discovery and artifact files", async () => {
  const root = await fixture(
    `{ basePath: "/docs", ai: { ask: { enabled: true, endpoint: "https://ask.test/chat" }, mcp: { enabled: true } } }`
  );
  await mkdir(join(root, "public/.well-known"), { recursive: true });
  await writeFile(join(root, "public/.well-known/mcp.json"), '{"owned":true}');
  await writeFile(join(root, "public/llms.txt"), "Owned index");
  const project = await scanProject(root);
  await generateRuntime(project);
  expect(buildAgentReadability(project)?.artifacts.askApi).toBe(
    "https://ask.test/chat"
  );
  expect(
    existsSync(join(project.context.outDir, "src/pages/docs/api/ask.ts"))
  ).toBe(false);
  expect(
    existsSync(join(project.context.outDir, "src/blume-mcp/discovery.ts"))
  ).toBe(false);
  const endpoint = await import(
    join(project.context.outDir, "src/pages/docs/llms.txt.ts")
  );
  expect(await endpoint.GET().text()).toBe("Owned index");
  project.config.deployment.site = "https://docs.test";
  project.config.deployment.base = "/host";
  expect(buildAgentReadability(project)?.artifacts.llmsTxt).toBe(
    "https://docs.test/host/docs/llms.txt"
  );
  expect(buildAgentReadability(project)?.artifacts.mcp?.discovery).toBe(
    "https://docs.test/host/.well-known/mcp.json"
  );
  project.config.ai.mcp.discovery = false;
  await generateRuntime(project);
  expect(
    await readFile(join(root, "public/.well-known/mcp.json"), "utf-8")
  ).toBe('{"owned":true}');
});
